# Generated by Django 4.2.7 on 2023-11-15 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Добавьте название вашего файла', max_length=56, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-zА-Яа-я0-9_]+\\.txt$')], verbose_name='Имя файла')),
                ('data', models.TextField(verbose_name='Содержимое файла')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Текстовый файл',
                'verbose_name_plural': 'Текстовые файлы',
            },
        ),
    ]
